name: Build & Push Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (tuỳ chọn) Hỗ trợ multi-arch
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (multi-arch + cache)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile           # đổi nếu Dockerfile ở chỗ khác
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/jinhuntqt/gemini-balance:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/jinhuntqt/gemini-balance:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
